### ISSUE TITLE
Migrate to oclif

### ISSUE THREAD

**Issue by ianwremmel** [ianwremmel/clark#90]
- [ ] switch back to mocha via codemod (if needed) #91 
- [ ] run a codemod for oclif testing #92 
- [ ] migrate commands to oclif #93
